import type { PlayerWeaknessCategory } from '$lib/schemas/player-analysis';
import type { BasketballDrill } from '$lib/schemas/drill';

export const DRILLS_BY_WEAKNESS: Record<PlayerWeaknessCategory, BasketballDrill[]> = {
	dribbling: [
		{
			name: 'Right Hand Dribbling',
			difficulty: 'beginner',
			duration: '10-15 minutes',
			description: 'Practice dribbling with only your right hand',
			instructions: [
				'Stand in place, dribble 50 times with right hand',
				'Walk while dribbling with right hand (down and back court)',
				'Jog while dribbling with right hand',
				'Sprint while maintaining control with right hand',
				'Focus: Keep ball low, use fingertips, eyes up',
			],
			keyPoints: 'Control the ball at waist level, use your fingertips not palm, keep your eyes up',
		},
		{
			name: 'Left Hand Dribbling',
			difficulty: 'beginner',
			duration: '10-15 minutes',
			description: 'Practice dribbling with only your left hand',
			instructions: [
				'Stand in place, dribble 50 times with left hand',
				'Walk while dribbling with left hand (down and back court)',
				'Jog while dribbling with left hand',
				'Sprint while maintaining control with left hand',
				'Focus: Build muscle memory in non-dominant hand',
			],
			keyPoints: 'Same technique as right hand, build coordination in weak hand',
		},
		{
			name: 'Two-Ball Dribbling',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Dribble two basketballs simultaneously',
			instructions: [
				'Start standing still, dribble both balls at same time',
				'Progress to walking with both balls',
				'Try alternating dribbles (one high, one low)',
				'Practice crossovers with both balls',
				'Focus: Independent hand control',
			],
			keyPoints: 'Develops hand-eye coordination and ambidexterity',
		},
		{
			name: 'Crossover Dribble Drill',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Practice crossing the ball between hands',
			instructions: [
				'Dribble right hand, crossover to left (10 reps)',
				'Dribble left hand, crossover to right (10 reps)',
				'Figure-8 pattern between legs (20 reps)',
				'Crossover while moving forward',
				'Focus: Quick, low crossovers',
			],
			keyPoints: 'Ball should be below knee, protect with body',
		},
		{
			name: 'Between the Legs Dribble',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Practice dribbling between your legs',
			instructions: [
				'Stand with legs shoulder-width apart',
				'Dribble ball between legs from front to back (10 reps each direction)',
				'Walk forward while dribbling between legs',
				'Combine with crossover dribbles',
				'Focus: Control and speed',
			],
			keyPoints: 'Keep ball low, use fingertips, protect ball',
		},
		{
			name: 'Behind the Back Dribble',
			difficulty: 'advanced',
			duration: '10 minutes',
			description: 'Master behind-the-back dribbling',
			instructions: [
				'Practice stationary behind-back dribbles (10 reps each hand)',
				'Walk while doing behind-back dribbles',
				'Combine with crossovers and between-legs',
				'Use in game-like situations',
				'Focus: Smooth, controlled motion',
			],
			keyPoints: 'Advanced move for ball protection, practice slowly first',
		},
	],
	shooting: [
		{
			name: 'Form Shooting',
			difficulty: 'beginner',
			duration: '15-20 minutes',
			description: 'Perfect shooting form close to basket',
			instructions: [
				'Stand 3 feet from basket',
				'Shoot 25 shots focusing on form (BEEF: Balance, Eyes, Elbow, Follow-through)',
				'Move to 5 feet, shoot 25 more',
				'Move to 10 feet, shoot 25 more',
				'Focus: Consistent shooting motion every time',
			],
			keyPoints: 'BEEF principle: Balance, Eyes on target, Elbow in, Follow-through',
		},
		{
			name: 'Pull-Up Jump Shot',
			difficulty: 'intermediate',
			duration: '15 minutes',
			description: 'Shoot while moving and pulling up',
			instructions: [
				'Dribble towards basket, pull up at free throw line (10 reps)',
				'Pull up from different distances',
				'Practice from both sides of court',
				'Add hesitation moves before pull-up',
				'Focus: Balance and elevation on jump',
			],
			keyPoints: 'Stop on balance, elevate straight up, follow through',
		},
	],
	'free-throw-shooting': [
		{
			name: 'Free Throw Practice',
			difficulty: 'beginner',
			duration: '10 minutes',
			description: 'Master free throw shooting',
			instructions: [
				'Develop consistent routine: dribble, breathe, shoot',
				'Shoot 20 free throws, track percentage',
				'Practice under pressure: make 10 in a row',
				'Visualize game situations',
				'Focus: Same routine every time',
			],
			keyPoints: 'Routine is key, relax, follow through',
		},
	],
	'three-point-shooting': [
		{
			name: 'Catch and Shoot',
			difficulty: 'intermediate',
			duration: '15 minutes',
			description: 'Practice shooting off the catch',
			instructions: [
				'Partner passes you the ball from various spots',
				'Catch and shoot immediately (20 shots from each spot)',
				'Practice from three-point line',
				'Add game-like movement: curl, fade, etc.',
				'Focus: Quick release, square to basket',
			],
			keyPoints: 'Catch in shooting position, quick release, follow through',
		},

		{
			name: 'Three-Point Shooting',
			difficulty: 'intermediate',
			duration: '20 minutes',
			description: 'Improve three-point accuracy',
			instructions: [
				'Shoot 25 shots from 5 spots around three-point line',
				'Practice catch-and-shoot threes',
				'Practice shooting off the dribble',
				'Game situation: shoot with defender closing out',
				'Focus: Consistent arc and follow-through',
			],
			keyPoints: 'Generate power from legs, consistent arc, follow-through',
		},
	],
	passing: [
		{
			name: 'Chest Pass Drill',
			difficulty: 'beginner',
			duration: '10 minutes',
			description: 'Perfect chest passing technique',
			instructions: [
				'Partner stands 10 feet away',
				'Chest pass 50 times, focus on form',
				'Move to 15 feet, chest pass 30 times',
				'Pass with defender closing out',
				'Focus: Two hands, snap through, follow through',
			],
			keyPoints: 'Two hands on ball, thumbs down on release, step into pass',
		},
		{
			name: 'Bounce Pass Drill',
			difficulty: 'beginner',
			duration: '10 minutes',
			description: 'Master the bounce pass',
			instructions: [
				'Bounce pass to partner (50 reps)',
				'Practice from different distances',
				'Bounce point should be 2/3 distance to target',
				'Use in game situations (passing around defender)',
				'Focus: Right bounce point, proper angle',
			],
			keyPoints: 'Bounce point is key - not too close, not too far',
		},
		{
			name: 'Outlet Pass Drill',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Practice rebounding and outlet passing',
			instructions: [
				'Grab rebound, pivot, outlet pass to teammate',
				'Practice from both sides',
				'Add pressure (defender closing out)',
				'Focus on speed and accuracy',
				'Repeat 30 times',
			],
			keyPoints: 'Pivot quickly, pass to numbers on fast break',
		},
		{
			name: 'Skip Pass Drill',
			difficulty: 'advanced',
			duration: '10 minutes',
			description: 'Pass across court to open teammate',
			instructions: [
				'Partner on opposite side of court',
				'Practice skip passing over defense',
				'Add game-like situations',
				'Focus on accuracy and timing',
				'20 reps each side',
			],
			keyPoints: 'High arc to clear defense, lead your teammate',
		},
	],
	rebounding: [
		{
			name: 'Box Out Drill',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Master the box out technique',
			instructions: [
				'Partner shoots, you box out',
				'Maintain contact, find ball',
				'Practice from different angles',
				'Focus: Butt to opponent, arms wide',
				'Repeat 20 times',
			],
			keyPoints: 'Butt to opponent, wide base, find the ball',
		},
		{
			name: 'Reaction Rebound Drill',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Improve rebounding reaction time',
			instructions: [
				'Coach shoots from various spots',
				'Sprint to rebound (offensive and defensive)',
				'Practice securing ball with two hands',
				'Add outlet pass after rebound',
				'Focus: Read trajectory, pursue aggressively',
			],
			keyPoints: 'Read the shot, anticipate where ball will go, secure with two hands',
		},
		{
			name: 'Tip Drill',
			difficulty: 'advanced',
			duration: '10 minutes',
			description: 'Practice tipping rebounds',
			instructions: [
				'Partner shoots, you tip ball to yourself',
				'Practice tipping to teammate',
				'Work on timing and elevation',
				'Focus: Quick hands, multiple tips',
				'20 reps',
			],
			keyPoints: 'Quick hands, jump with purpose, control tips',
		},
	],
	defense: [
		{
			name: 'Defensive Slide Drill',
			difficulty: 'beginner',
			duration: '10 minutes',
			description: 'Improve lateral movement and defensive stance',
			instructions: [
				'Start in defensive stance (knees bent, weight on balls of feet)',
				'Slide right 10 steps, slide left 10 steps',
				"Keep body low, don't cross feet",
				'Add drop step on direction changes',
				'Focus: Stay low, maintain stance',
			],
			keyPoints: "Low stance, wide base, slide don't cross, stay on balls of feet",
		},
		{
			name: 'Close-Out Drill',
			difficulty: 'intermediate',
			duration: '10 minutes',
			description: 'Practice closing out on shooters',
			instructions: [
				'Start under basket, coach/partner at three-point line',
				'Sprint to close out, stop in defensive stance',
				'Contest shot with high hand',
				'Practice closing out from different angles',
				'Focus: Quick close, controlled stop',
			],
			keyPoints: 'Sprint to 3 feet, then close out under control, high hand contest',
		},
		{
			name: 'One-on-One Defense',
			difficulty: 'intermediate',
			duration: '15 minutes',
			description: 'Defend live offensive player',
			instructions: [
				'Defend offensive player for 10 seconds',
				'Prevent drive, contest shot',
				'Focus on staying in front',
				'Practice different positions (guard, wing, post)',
				'Focus: Anticipate, react, stay balanced',
			],
			keyPoints: 'Stay in stance, keep ball in front, move feet not hands',
		},
	],
	// FIXME: Unused drills below
	// footwork: [
	// 	{
	// 		name: 'Pivot Drill',
	// 		difficulty: 'beginner',
	// 		duration: '10 minutes',
	// 		description: 'Master pivoting on both feet',
	// 		instructions: [
	// 			'Hold ball, pivot on right foot (forward pivot 10x, reverse 10x)',
	// 			'Pivot on left foot (forward 10x, reverse 10x)',
	// 			'Add chair to pivot around',
	// 			'Practice with defender',
	// 			'Focus: Keep pivot foot down, protect ball',
	// 		],
	// 		keyPoints: 'Keep pivot foot planted, pivot on ball of foot, protect ball',
	// 	},
	// 	{
	// 		name: 'Triple Threat Position',
	// 		difficulty: 'beginner',
	// 		duration: '10 minutes',
	// 		description: 'Practice triple threat stance',
	// 		instructions: [
	// 			'Catch ball, get into triple threat (shot, pass, dribble)',
	// 			'Practice jab steps from triple threat',
	// 			'Pivot from triple threat',
	// 			'Focus on balance and readiness',
	// 			'50 reps',
	// 		],
	// 		keyPoints: 'Knees bent, ball at shooting pocket, ready to act',
	// 	},
	// ],
	// conditioning: [
	// 	{
	// 		name: 'Suicide Runs',
	// 		difficulty: 'intermediate',
	// 		duration: '10 minutes',
	// 		description: 'Build speed and endurance',
	// 		instructions: [
	// 			'Run to free throw line and back',
	// 			'Run to half court and back',
	// 			'Run to opposite free throw and back',
	// 			'Run full court and back',
	// 			'Rest 2 minutes, repeat 3 times',
	// 		],
	// 		keyPoints: 'Maintain form, touch each line, push through fatigue',
	// 	},
	// 	{
	// 		name: 'Defensive Slide Conditioning',
	// 		difficulty: 'intermediate',
	// 		duration: '10 minutes',
	// 		description: 'Combine defense and conditioning',
	// 		instructions: [
	// 			'Defensive slide full court width 5 times',
	// 			'Sprint back, repeat',
	// 			'Maintain defensive stance throughout',
	// 			"Focus: Don't sacrifice form for speed",
	// 			'Rest 1 minute between sets (3 sets)',
	// 		],
	// 		keyPoints: 'Stay low, maintain form, build game-like endurance',
	// 	},
	// ],
};
